sudo: false
language: python
cache: pip

env:
  global:
    - CARGO_HOME="$HOME/.cargo"
    - PATH="$PATH:$CARGO_HOME/bin"

cache:
  directories:
  - $CARGO_HOME
  - $HOME/.pip/cache

python:
- '2.7'
- '3.5'
- '3.6'
- nightly

before_install:
- curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
- pip install -U setuptools setuptools_rust

install:
- python setup.py build
- pip install .

script:
- python setup.py test

before_deploy:
- pip install restructuredtext_lint
- rst-lint README.rst

notifications:
  email:
  - althonosdev@gmail.com
